name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./SampleWebAPI.sln

    - name: Build
      run: dotnet build ./SampleWebAPI.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./SampleWebAPI.sln --configuration Release --no-restore --verbosity normal
