name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Solution_Name: SampleWebAPI.sln
      Configuration: Release

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ env.Configuration }} --no-restore

    - name: Test
      run: dotnet test ${{ env.Solution_Name }} --configuration ${{ env.Configuration }} --no-restore --verbosity normal
